### ISSUE TITLE
As a person who wants to organize their time with a calendar app, I want to log in to the calendar app with my credentials so that I can see my schedule on the calendar.

### ISSUE THREAD

**Issue by jtsang3** [cse442-at-ub/project_s23-the-fellas#12]
**Acceptance Tests**

*Test 1*
1) Go to [the login page of the web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php)
2) Log in with username jtsang3 and empty password
3) Click the "login" button
4) Verify that the login failed and that the login page is visible on the screen

*Test 2*
1) Go to [the login page of the web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php)
2) Log in with username jtsang3 and password test
3) Click the "login" button
4) Verify that a calendar screen is visible

**Comment by skoplum** [comment]
Please include a link to the login page for the website.
