### ISSUE TITLE
As a student who needs to plan out deadlines and assignments, I want to click a button to add an event to my schedule so I can see the new event on my schedule.

### ISSUE THREAD

**Issue by jtsang3** [cse442-at-ub/project_s23-the-fellas#13]
**Acceptance Tests**

*Test 1*
1) Go to [the login page for the calendar app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php)
2) Enter your ubitname for username and password: test
3) Click the login button
4) Click the Add Event button.
5) Type in "Event name" for event name.
6) Select a date.
7) Click add event button in add event window.
8) Verify that the new event is on the calendar.
9) Verify that the new event information matches what was entered in the add event window.

**Comment by skoplum** [comment]
Please include a link to the login page for the website.
