### ISSUE TITLE
As a user who likes ease of access, I would like tabs that can navigate me to different sections of the application with ease.

### ISSUE THREAD

**Issue by D1Taylor06** [cse442-at-ub/project_s23-the-fellas#14]
**Acceptance Test:**

*Test 1*
1) Goto https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/
2) Log In
3) Verify the navigation bar is at the top of the page
4) Verify that the buttons direct you to their labeled pages

*Test 2*
1) Goto https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/
2) Log In
3) Verify the log out button returns you to the login page.

**Comment by skoplum** [comment]
We'll need to address the "placeholder" as our web app gains more functionality. Keeping in "In-Progress" pipeline.
