### ISSUE TITLE
As an artistic user, I would like to be taken to my profile page to edit my profile

### ISSUE THREAD

**Issue by devinclem** [cse442-at-ub/project_s23-the-fellas#16]
**Acceptance Test:**

*Test 1*
- Navigate to: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php
- Log in using: username: devincle8 password: devin
- Click the profile icon at the top right to go to [the profile page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/editProfile.php)
- Ensure profile page appears

**Comment by skoplum** [comment]
Please include a link to the profile page on the web server.
