### ISSUE TITLE
Create a functioning weekly calendar using PHP

### ISSUE THREAD

**Issue by drboyle2** [cse442-at-ub/project_s23-the-fellas#17]
**Task Test:**

*Test 1*
-  Visit: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/
-  Log into the calendar app with username: devincle8 and password: devin
- Click "Add Event" 
- Choose an event title/day and click submit
- Ensure that the newly created event is showing on the correct day
- Repeat steps 2-4 for numerous different days and ensure behavior maintains consistent

**Comment by skoplum** [comment]
Please revise your task tests to be more instructive and include a link to the calendar on the web server.

**Comment by skoplum** [comment]
We also need to utilize/create some User Story as a dependency for this Task. Preferably one that can be used throughout the remainder of Sprint 3 and Sprint 4 with acceptance tests.

**Comment by skoplum** [comment]
We can move this task to "Completed" since the basic functionality is implemented.
