### ISSUE TITLE
Implement code to add all events associated with a given username from the database to the calendar page

### ISSUE THREAD

**Issue by jtsang3** [cse442-at-ub/project_s23-the-fellas#31]
**Task Tests**

*Test 1*
1) Go to the [login page of the web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php) and log in with username devincle and password test.
2) Click the Add Event button in the top left corner.
3) Enter event title: test and current datetime for event date and time
4) Click submit
5) Verify that there is an event with the name test under the current date on the calendar
6) Click the Add Event button
7) Enter event title: test2 and current datetime for event date and time
8) Click submit
9) Verify that there are two events under the current date on the calendar - one labeled test and the other labeled test2

*Test 2*
1) Go to the[login page of the web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php) and log in with username devincle and password test.
2) Click the Add Event button in the top left corner.
3) Enter event title: test and current datetime for event date and time
4) Click submit
5) Verify that there is an event with the name test under the current date on the calendar
6) Click the Log Out button in the top right corner.
7) Log in with username drboyle2 and password test.
8) Click the Add Event button in the top left corner.
9) Enter event title: exam and current datetime for event date and time
10) Click submit
11) Verify that there is an event with the name exam under the current date on the calendar.
12) Verify that there are no other events on the calendar besides the exam event.

**Comment by skoplum** [comment]
Please add links to the homepage
