### ISSUE TITLE
As someone who manages many appointments and tasks, I want to add multiple events to my calendar so that I can see multiple events on my calendar.

### ISSUE THREAD

**Issue by devinclem** [cse442-at-ub/project_s23-the-fellas#4]
**Acceptance Tests**

*Test 1*
1) Go to [the login page of the calendar app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php)
2) Type in username: jtsang3 and password: test
3) Click the login button
4) Click the Add Event button in the top-left corner
5) Enter Event Title: exam and for Event Date and Time, select the current date, 12:00 pm
6) Click the Submit button
7) Verify that the monthly calendar is visible on the screen
6) Verify that on the calendar under the current date, there is a box with the label exam.

*Test 2*
1) Go to [the login page of the calendar app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php)
2) Type in username: jtsang3 and password: test
3) Click the login button
4) Click the Add Event button in the top-left corner
5) Enter Event Title: exam and for Event Date and Time, select the current date, 12:00 pm
6) Click the Submit button
7) Click the Add Event button in the top-left corner
8) Enter Event Title: class and for Event Date and Time, select the current date, 3:00 pm
9) Click the Submit button
10) Verify that on the calendar under the current date, there are two boxes - one labeled exam and another labeled class.

*Test 3*
1) Go to [the login page of the calendar app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442c/login.php)
2) Type in username: jtsang3 and password: test
3) Click the login button
4) Click the Add Event button in the top-left corner
5) Enter Event Title: exam and for Event Date and Time, select the current date, 12:00 pm
6) Click the Submit button
7) Click the Add Event button in the top-left corner
8) Enter Event Title: class and for Event Date and Time, select the current date, 3:00 pm
9) Click the Submit button
10) Click the Add Event button in the top-left corner
11) Enter Event Title: club meeting and for Event Date and Time, select the current date, 5:21 pm
12) Click the Submit button
13) Verify that on the calendar under the current date, there are three boxes - one labeled exam, another labeled class, and another labeled club meeting.

**Comment by skoplum** [comment]
Please rewrite the Acceptance Tasks for this User Story so that an untrained user can complete them with no issue.
